### ISSUE TITLE
Error: URLs is malformed. Please use only absolute URLs

### ISSUE THREAD

**Issue by malikmoss** [Hendrixer/fullstack-music#13]
**Receiving this error from next.js due to the '/signin' route.**

I resolved by hardcoding 'https://localhost3000/signin' but I was wondering if anyone had a more dynamic solution?

```
import { NextResponse } from 'next/server'

const signedinPages = ['/', '/playlist', '/library']

export default function middleware(req) {
  if (signedinPages.find((p) => p === req.nextUrl.pathname)) {
    const token = req.cookies.TRAX_ACCESS_TOKEN

    if (!token) {
      return NextResponse.redirect('/signin')
    }
  }
}
```

**Comment by dsyph3r** [comment]
@malikmoss There's a [Pull Request](https://github.com/Hendrixer/fullstack-music/pull/11) open by another developer that shows how to do this dynamically.

**Comment by malikmoss** [comment]
@dsyph3r thank you!
